/**
 * The only icons the Movie Studio may use: the 66 Lucide glyphs of the web Movie Studio (65 Studio
 * glyphs + bell-ring for the shared push-nudge banner). Pure list so a unit test can enforce it.
 * shuffle, dices and eraser exist only for the optional demo/dev controls and are not used.
 */
export const STUDIO_ICON_NAMES = [
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'bell-ring',
  'briefcase-business',
  'calendar-days',
  'check',
  'check-check',
  'chevron-down',
  'chevron-right',
  'chevron-up',
  'circle-check',
  'circle-play',
  'circle-x',
  'clapperboard',
  'cloud-upload',
  'coins',
  'columns-2',
  'crop',
  'dices',
  'download',
  'eraser',
  'file-text',
  'film',
  'folder-clock',
  'history',
  'house',
  'image',
  'image-plus',
  'images',
  'layers',
  'loader-circle',
  'maximize-2',
  'megaphone',
  'menu',
  'message-square',
  'monitor-play',
  'music',
  'panel-left',
  'panel-right',
  'panel-top',
  'panels-top-left',
  'play',
  'plus',
  'rectangle-vertical',
  'refresh-cw',
  'rotate-ccw',
  'route',
  'save',
  'scissors',
  'shuffle',
  'sliders-horizontal',
  'sparkles',
  'square',
  'square-play',
  'trash-2',
  'triangle-alert',
  'tv',
  'user-round',
  'users',
  'video',
  'wand-sparkles',
  'x',
  'zoom-in',
  'zoom-out',
] as const;

export type StudioIconName = (typeof STUDIO_ICON_NAMES)[number];
